Update duplicity to 0.6.16.
while here,
* LICENSE=gnu-gpl-v2
* no need to buildlink with py-boto, simple DEPENDS is sufficient.
* no need to depend on py-gnupg, this package contains own one.
* fixes locale dir.
* distutils package, register egg-info.

New in v0.6.16 (2011/10/16)
----------------------------
Enhancements:
- Usability enhancement: sign passphrase prompt has no second
  verification prompt anymore, symmetric passphrases are
  still verified
- Fixed Unicode errors when translations are used.
- Replaced old tarfile.py with Python 2.7 version, modded
  to support Python 2.4 syntax.

Bugs closed in this release:
485219     Fixed fields are not fixed, leading to buffer overflows...
676109     Amazon S3 backend multipart upload support
690549     uid and guid setting adversely affects integrity
739438     Local backend should always try renaming instead of copying
832149     Uploads to Rackspace fail silently
835892     duplicity crash: "AssertionError: rb None None"
838162     Duplicity URL Parser is not parsing IPv6 properly
838264     Duplicity thinks partial encrypted backups are not encrypted
870116     Duplicity does not handle UIDs higher than 60001

Merges:
lp:~ed.so/duplicity/reuse-passphrase-for-signing-fix
lp:~mterry/duplicity/cloudfiles-10k
lp:~duplicity-team/duplicity/check-volumes
lp:~mterry/duplicity/tarfile
lp:~mterry/duplicity/partial-encryption
lp:~mterry/duplicity/fix-local-backend-validation
lp:~ross-ross-williams/duplicity/gpg-agent-fix
lp:~mterry/duplicity/rbNoneNone
lp:~ed.so/duplicity/UnicodeDecodeError


New in v0.6.15 (2011/08/19)
----------------------------
Enhancements:
- Ignore 404 errors when deleting a file on Ubuntu One.
- Ignore ENOENT (file missing) errors where it is safe.
- Set minimum Python version to 2.4 in README.
- introduce --numeric-owner parameter
  patch courtesy of Lukas Anzinger <l.anzinger AT gmail.com>
- duplicity:restore_check_hash
  "Invalid data - *** hash mismatch" lists the offending filename
- fixes to unit tests to support SIGN_PASSPHRASE

Bugs closed in this release:
524922     duplicity does not have numeric uid/gid support
703142     AssertionError: assert len(chain_list) == 2
794576     Transport endpoint is not connected
815635     Bad passphrase can leave bogus sigtar in archive
818178     Shouldn't try to delete files it knows don't exist
821368     Error doing backup of the .evolution folder
823556     sftp errors after rev 740 change
824678     0.6.14 Fails to install on 8.04 LTS (Hardy)

Merges:
lp:~mterry/duplicity/u1-ignore-404
lp:~mterry/duplicity/guard-tarinfo
lp:~mterry/duplicity/enotconn
lp:~mterry/duplicity/look-at-partials-during-sync
lp:~mterry/duplicity/more-accurate-sync
lp:~mterry/duplicity/report-encrypted-chains
lp:~mterry/duplicity/815635
lp:~mterry/duplicity/retry-u1
lp:~mterry/duplicity/818178
lp:~ed.so/duplicity/encr-sign-key2
lp:~mterry/duplicity/u1-fixes
lp:~carlos-abalde/duplicity/google-docs
lp:~ed.so/duplicity/numowner+hashverbose


New in v0.6.14 (2011/06/18)
----------------------------
Enhancements:
452342     Provide Ubuntu One integration

Bugs closed in this release:
433591     AttributeError: FileobjHooked instance has no attribute 'name'
487720     Restore fails with "Invalid data - SHA1 hash mismatch"
507904     Cygwin: Full Backup fails with "IOError: [Errno 13] Permission denied"
512628     --exclude-filelist-stdin and gpg error with/without PASSPHRASE
680425     Endless retype passphrase when typo
705499     "include-filelist-stdin" not implemented on version 0.6.11
739438     [PATCH] Local backend should always try renaming instead of copying
753858     cannot import name S3ResponseError
761688     Difference found: File X has permissions 666, expected 666
777377     collection-status asking for passphrase
778215     ncftpls file delete fails in ftpbackend.py
782294     create tomporary files with sftp
782321     duplicity sftp backend should ignore removing a file which is not there
792704     Webdav(s) url scheme lacks port support
782294     create tomporary files with sftp
782337     sftp backend cannot create new subdirs on new backup
794123     Timeout on sftp command 'ls -1'
797758     Duplicity ignores some FatalErrors
793096     Allow to pass different passwords for --sign-key and --encrypt-key

Merges:
lp:~ed.so/duplicity/0.6-add_sftp
lp:~ed.so/duplicity/0.6-nonfatal-exclude
lp:~lekensteyn/duplicity/multipass
lp:~mterry/duplicity/797758
lp:~mterry/duplicity/gio-name
lp:~mterry/duplicity/levelName
lp:~mterry/duplicity/retry-decorator
lp:~mterry/duplicity/u1-status


New in v0.6.13 (2011/04/02)
----------------------------
Enhancements added this release:
New manual test to make Ctrl-C issues easier to replicate.
Use python-virtualenv to make testing multiple Python versions easier.
In boto backend check for existing bucket before trying to create.

Bugs closed in this release:
579958     Assertion error "time not moving forward at appropriate pace"
613244     silent data corruption with checkpoint/restore
731905     File "/usr/bin/duplicity", error after upgrade from 6.11 to 6.12


New in v0.6.12 (2011/03/08)
----------------------------
Enhancements added this release:
626915     ftps support using lftp (ftpsbackend)

Bugs closed in this release:
486489     Only full backups done on webdav
578663     Use log codes for common backend errors
581054     Inverted "Current directory" "Previous directory" in error message
620163     OSError: [Errno 2] No such file or directory
629136     sslerror: The read operation timed out with cf
629984     boto backend uses Python 2.5 conditional
655797     symbolic link ownership not preserved
670891     Cygwin: TypeError: basis_file must be a (true) file ...
681980     Duplicity 0.6.11 aborts if RSYNC_RSH not set
700390     Backup fails silently when target is full (sftp, verbosity=4)
704314     Exception in log module

Merges:
lp:~mterry/duplicity/backend-log-codes3
lp:~blueyed/duplicity/path-enodev-bugfix


New in v0.6.11 (2010/11/20)
----------------------------
Bugs closed in this release:
433970     Add an option to connect to S3 with regular HTTP (and not HTTPS)
578663     Use log codes for common backend errors
631275     missing ssh on rsyncd url - rsync: Failed to exec ssh: ...
635494     backed up to S3, wiped drive, reinstalled, unable to restore backup
637556     os.execve should get passed program as first argument
669225     sftp: "Couldn't delete file: Failure'" only logged on level 9
655468     0.6.10 does not work with S3
674506     RsyncBackend instance has no attribute 'subprocess_popen_persist'

Merges:
lp:~blueyed/duplicity/bug-669225
lp:~duplicity-team/duplicity/po-updates
lp:~ed.so/duplicity/0.6.10-backend_fixes
lp:~ed.so/duplicity/RSYNC_RSH-fix
lp:~ed.so/duplicity/sign_symmetric2
lp:~ed.so/duplicity/survive_spaces
lp:~l2g/duplicity/use-py.test
lp:~mbp/duplicity/433970-non-ssl


New in v0.6.10 (2010/09/19)
----------------------------
Bugs closed in this release:
542482     Offer command to remove old incremental backups from target
578663     Use log codes for common backend errors
589495     duplicity --short-filenames crashes with TypeError
612714     NameError: global name 'parsed_url' is not defined
613448     ftpbackend fails if target directory doesn't exist
615449     Command-line verbosity parsing crash


New in v0.6.09 (2010/07/25)
----------------------------
Bugs closed in this release:
502609     Unknown error while uploading duplicity-full-signatures
539393     Duplicity returns 1 when continuing an interrupted backup
550455     duplicity doesn't handle with large files well
567738     --ssh-options options passing options to ssh do not work
576564     username not url decoded in backend (at least rsync)
579958     Assertion error "time not moving forward at appropriate pace"
582962     Diminishing performance on large files

Upgraded tahoebackend to new parse_url.
Fix to warning message in sshbackend.


New in v0.6.08b (2010/03/11)
----------------------------
Fix bug where encrypted backup without --gpg-options crashes.
This was a followup issue to bug 490619 released in 0.6.07.
This is attempt #2 -- not sure what happened to the patch,
but it did not show up in 0.6-series like it should have.


New in v0.6.08a (2010/03/11)
----------------------------
Fix bug where encrypted backup without --gpg-options crashes.
This was a followup issue to bug 490619 released in 0.6.07.


New in v0.6.08 (2010/03/07)
---------------------------
Bugs closed in this release:
519110     Need accurate man page info on use of scp/sftp usage.
532051     rdiffdir attempts to reference undefined variables with some command arguments
529869     TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
530910     TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'


New in v0.6.07 (2010/02/28)
---------------------------
Bugs closed in this release:
459511     --tempdir option doesn't override TMPDIR
467391     [PATCH] WebDAV backend doesn't work
487686     re-add scp backend and make available via command line option
490619     Use optparse not getopt
497243     0.6.06, archive dir: cache desynchronization caused by remove*
501093     SSHBackend doesn't handle spaces in path
505739     "sslerror: The read operation timed out" with S3
520470     Don't Warn when there's old backup to delete
522544     OSError: [Errno 40] Too many levels of symbolic links
388673     Allow renaming paths as they are restored


New in v0.6.06 (2009/10/29)
---------------------------
Merged in lp:~mterry/duplicity/list-old-chains
List/keep old signature chains

Applied patches from Kasper Brand that fixed device file handling.
http://lists.gnu.org/archive/html/duplicity-talk/2009-09/msg00001.html

Merged in lp:~l2g/duplicity/flag-transl-comments which cleared up how
translation comments should be passed to the translators cleanly now.

Applied 422477; [PATCH] IMAP Backend Error in delete()

Merged in lp:~mterry/duplicity/iterate-warnings
Add machine codes to various warnings when iterating over source files

Fix problems with unittests under Jaunty.  It appears that redirection
in os.system() has changed for the worse, so a workaround for now.

Fix problem in restart where there were no manifest entries and no
remote volumes stored.  We clean out the partial and restart.

Fixed 435975 gpg asks for password in 0.6.05, but not in 0.5.18


New in v0.6.05 (2009/08/28)
---------------------------
Merged in lp:~l2g/duplicity/test-compat from Larry Gilbert which made
the testing compatible across more systems.  Also fixed the remaining
collectionstest bug which was trying to test with no cache present.

Bugs fixed this release:
407968  GIO backend can't restore
408059  Failure due to _logger.log failure for content with special
        characters: TypeError decoding Unicode not supported
409593  deja-dup (or duplicity) deletes all signatures
412667  "duplicity remove-older-than" asks for passphrase even though
        not required
418170  [PATCH] file names longer then 512 symbols are not supported


New in v0.6.04 (2009/08/01)
---------------------------
One major and one minor change.  The "No such file or directory" error
is bad enough that this should be released quickly.  For those of you
using encryption, this is not a problem, but for those of you that do
not use encryption (--no-encryption), then this will manifest itself if
the local cache gets out of sync with the remote store.

Bugs fixed this release:
405734  duplicity fails to restore files that contain a newline character
403790  Backup error: No such file or directory


New in v0.6.03 (2009/07/29)
---------------------------
Lots of small changes and some bug fixes.
* Restart error handling has been smoothed out a great deal and it
  "does what is right" in order to keep going.
* Backends are now optional, if they fail an Info message is put out
  to notify of the failure and why.
* There was more work on translations and internationalization.
Thanks to everyone!

Bugs fixed this release:
377528  --file-to-restore doesn't work with trailing slash
394757  Backend imports should be made optional
398230  Deja-dup backup fails with message: "Unable to locate last file"
401303  0.6.2 manpage inconsistent wrt. archive-dir/name
405646  Small i18n error
405975  duplicity.gpg.gpg_failed() breaks and spews on GnuPG error
402794  duplicity public-key-only incompatible with gnupg 2.0.11


New in v0.6.02 (2009/07/07)
---------------------------
Duplicity will now remove any spurious files left in the cache from
a previous run.  This will keep the metadata cache in sync with the
remote storage metadata.

Bugs fixed this release:
394629  Hang on first collection-status
379386  Fix 'list-current-files' with missing archive dir
395826  "No such file or directory" when backing up second time
394627  User-friendly archive dir print
388699  Manifest mismatch error


New in v0.6.01 (2009/07/01)
---------------------------
Fixed issues in Checkpoint/Restart:
* The --name backupname" option was added to allow the
  user to separate one archive from another.  If not
  specified, the default is an MD5 hash of the target
  URL, which should suffice for most uses.

* The archive_dir (cache) is now stored in a standard
  location, defaulting to ~/.cache/duplicity.  See
  http://standards.freedesktop.org/basedir-spec/latest/

* The interaction between the --archive-dir option and
  the --name option allows for four possible results
  for the location of the archive dir.
    - neither specified (default)
      ~/.cache/duplicity/hash-of-url
    - --archive-dir=~/arch, no --name
      ~/arch/hash-of-url
    - no --archive-dir, --name=foo
      ~/.cache/duplicity/foo
    - --archive-dir=~/arch, --name=foo
      ~/arch/foo

* duplicity will now copy needed metadata from the
  remote store to the local cache as needed.  This
  means that the first use after upgraded from 0.5.x
  will have the metadata copied to the local archive
  dir in order to sync both.

* cleanup will now work correctly with the archive
  dir and separates the local from the remote files.

Bugs fixed this release:
* 388034     Unable to backup
* 378940     python2-6 issue / UTF-8 charset / Ubuntu 9.04
* 379386     Fix list-current-files w/ missing archive dir
* 387102     Asynchronous upload not working properly
* 387218     Make scp/ssh into sftp-only backend
* 388992     List of Orphaned Files Growing
* 392905     NoneType object has no attribute 'startswith'
* 393372     Error creating directory
* 383412     Add InfoCodes for upload events
* 383419     Add gio backend


New in v0.6.00 (2009/06/08)
---------------------------
Checkpoint/Restart capability added.  Checkpoint is
done at every volume written and Restart is done at
start of the next volume in the set.  Changes to
normal operations include a permanent duplicity
archive-dir at ~/.duplicity to save state.

To accomplish this, the signature and archive files
in the archive-dir now have three states:
1) temporary until the first volume has been written,
2) partial until the final volume has been written and
   sent to remote storage,
3) permanent with the same name as always.

Assumptions are made that if a restart is needed, then
all arguments are the same as before and that no files
have been removed from the file system between runs.

From now on, the --archive-dir option can be used to
change the location of the archive dir, but you are
responsible for moving the files if you change it.

Other fixes:
Unicode filenames in log messages are now OK.

Fixed problem where Cygwin was returning -1 for the
hard max open file limit.