need newer libXi dependency due to:
gdkinputprivate.h:38:35: error: X11/extensions/XInput.h: No such file or directory

(header got switched to different package)