remove incomplete libtoolization. I don't remember what problem I was trying to solve here, but the new libtool doesn't like being used like this, and it doesn't seem to be needed. Fixes failure observed in bulk build.
XXX there's still a PLIST problem:
ERROR: The following files are in the PLIST but not in /usr/pkg:
ERROR:         /usr/pkg/lib/gauche/0.9/x86_64--netbsd/gauche--threads.so
ERROR:         /usr/pkg/share/gauche/0.9/lib/gauche/threads.scm