Update from version 1.55 to 1.59.
Pkgsrc changes:
 o Fix a problem with using p5-Test-Output (optional, not DEPENDS+= here)

Upstream changes (from README file; missing updated Changes reported):
    Version 1.59 (2008/06/01)
        Better tests, better Meta.yml.

    Version 1.58 (2008/05/28)
        Another attempt at cleanup, as well expanding the Meta.yml file.

    Version 1.57 (2008/05/28)
        Cleaned up the Mac-specific files that were getting created in the
        archive.

    Version 1.56 (2008/05/27)
        Added the start of a testing suite. In the process, I found an
        error: HTML defines the tag 'NOFRAMES', not 'NOFRAME'. Both are
        currently in the tag list, but consider 'NOFRAME' depriciated.

        The test suite requires Test::More and Test::Output.