configure checks for glib 2.17.3 so require at least that for BUILDLINK_API_DEPENDS.glib2.
(tested with 2.16.3 and it failed with:
../pango/pango-enum-types.h:12:9: error: macro names must be identifiers)