databases/postgresql83-server: Fix rpath of plpgsql.so
Due to updated PKG_DEVELOPER checks, postgresql83-server started failing
with the following message:

ERROR: lib/postgresql/plpgsql.so: missing libintl.so.8

The plpgsql.so library had no rpath set other than what the base compiler
adds by default.  On DragonFly, the libintl.so library would likely have
been found anyway as /usr/pkg/lib is part of the LD_CONFIG hint file
search path, but that isn't a guarantee.

The new patch adds ${libdir} to the plpgsql.so rpath so it passes
PKG_DEVELOPER checks now.