Update to libXfont-1.3.3.  Changes:
commit 11edbc3a818e15ea2b622b31e6f87159ee68ae4a

    Do not call FT_Get_BDF_Charset_ID() if configured with
    --disable-bdfformat

commit 1ab07ce0eec4f6c7ed66c7aba3edf8c4315dd907

    FontFileDirectoryChanged: check length of "fonts.alias" as well
    as "fonts.dir"

commit 0f9db4aa7de6e0644ac9c5811b949e5f936c9d61

    Don't allow a font alias to point to itself and create a loop

    Part of fix for Sun bug 4258475
    <http://bugs.opensolaris.org/bugdatabase/view_bug.do?bug_id=4258475>

commit 754cabe62e91b9ad50c3027c063f4269775f7add

    Add missing include in src/FreeType/ftfuncs.c

    Fixes compiler warning:
    ../../../src/FreeType/ftfuncs.c:
	In function 'restrict_code_range_by_str':
    ../../../src/FreeType/ftfuncs.c:2081: warning:
	implicit declaration of function 'isspace'