Bump PKGREVISION of textproc/expat to 1: fix an obvious C bug where types should be declared/defined before they are used.  This should fix errors of the form:
.../expat.h:657: use of enum `XML_Status' without previous declaration
.../expat.h:736: multiple definition of `enum XML_Status'